force-app/main/default/objects/Employee__c/fields/ID_Number__c.field-meta.xml
<CustomField>
    <fullName>ID_Number__c</fullName>
    <label>ID Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ID Card</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Total cost of the Expense</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Expense</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/Expense_Distribution__c.object-meta.xml
<CustomObject>
    <label>Expense Distribution</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Distribution__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee related with the Expense Distribution</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <description>Total paid amount of the Expense Distribution</description>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Trip</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <description>Designation of the Trip (Ex: “Trip to Geneva”)</description>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomDatatableServiceTest.cls
@isTest
private class CustomDatatableServiceTest {
    
 @TestSetup
    static void setUp() {

        /*Employee__c newEmployee = new Employee__c(Name = 'Test Name', First_Name__c = 'Test First', Last_Name__c = 'Test Last', ID_Number__c= '777', ID_Type__c = 'Passport');
        insert newEmployee;

		Trip__c newTrip = new Trip__c(Name = 'Test Trip', Description__c = 'Test Description', Designation__c = 'Test Designation');
        insert newTrip;*/
    }
	@IsTest
    static void getExpensesTest() {

		Employee__c newEmployee = new Employee__c(Name = 'Test Name', First_Name__c = 'Test First', Last_Name__c = 'Test Last', ID_Number__c= '777', ID_Type__c = 'Passport');
        insert newEmployee;

		Expense__c newExpense = new Expense__c(Responsible__c = newEmployee.Id, Status__c = 'New', Cost__c = 10000);
        insert newExpense;

		List<Expense__c> listOfExpenses = CustomDatatableService.getExpenses();
		System.assertEquals(1, listOfExpenses.size());
    }

	@IsTest
    static void getTripsTest() {

		Trip__c newTrip = new Trip__c(Name = 'Test Trip', Description__c = 'Test Description', Designation__c = 'Test Designation');
        insert newTrip;

		List<Trip__c> listOfTrips = CustomDatatableService.getTrips();
		System.assertEquals(1, listOfTrips.size());
    }

	@IsTest
    static void getExpenseDistributionTest() {

		Employee__c newEmployee = new Employee__c(Name = 'Test Name', First_Name__c = 'Test First', Last_Name__c = 'Test Last', ID_Number__c= '777', ID_Type__c = 'Passport');
        insert newEmployee;

		Expense__c newExpense = new Expense__c(Responsible__c = newEmployee.Id, Status__c = 'New', Cost__c = 10000);
        insert newExpense;

		Expense_Distribution__c newExpenseDistributions = new Expense_Distribution__c(Employee__c = newEmployee.Id, Expense__c = newExpense.Id, Paid_Amount__c = 100);
        insert newExpenseDistributions;

		List<Expense_Distribution__c> listOfExpenseDistributions = CustomDatatableService.getExpenseDistributions();
		System.assertEquals(1, listOfExpenseDistributions.size());
    }

    @IsTest
    static void saveExpenseDistributionValuesTest(){
		Employee__c newEmployee = new Employee__c(Name = 'Test Name', First_Name__c = 'Test First', Last_Name__c = 'Test Last', ID_Number__c= '777', ID_Type__c = 'Passport');
        insert newEmployee;

		Expense__c newExpense = new Expense__c(Responsible__c = newEmployee.Id, Status__c = 'New', Cost__c = 10000);
        insert newExpense;

		Expense_Distribution__c newExpenseDistributions = new Expense_Distribution__c(Employee__c = newEmployee.Id, Expense__c = newExpense.Id, Paid_Amount__c = 100);

        List<Expense_Distribution__c> listOfNewExpenseDistributions = new List<Expense_Distribution__c>();
		listOfNewExpenseDistributions.add(newExpenseDistributions);
		insert listOfNewExpenseDistributions;
        for(Expense_Distribution__c item : listOfNewExpenseDistributions) {
			item.Paid_Amount__c = 200;
		}
		CustomDatatableService.saveExpenseDistributionValues(listOfNewExpenseDistributions);
		System.assertEquals(200, listOfNewExpenseDistributions[0].Paid_Amount__c);
	}

	@IsTest
    static void deleteExpenseDistributionRecordTest() {
	
		Expense__c newExpense = new Expense__c(Status__c = 'New', Cost__c = 10000);
        insert newExpense;
		
		Expense_Distribution__c newExpenseDistributions = new Expense_Distribution__c(Expense__c = newExpense.Id, Paid_Amount__c = 100);
		List<Expense_Distribution__c> listOfNewExpenseDistributions = new List<Expense_Distribution__c>();
		listOfNewExpenseDistributions.add(newExpenseDistributions);
		List<Id> listOfExpenseDistributionId = new List<Id>();
		for(Expense_Distribution__c item : listOfNewExpenseDistributions) {
			listOfExpenseDistributionId.add(item.Id);
		}
		CustomDatatableService.deleteExpenseDistributionRecord(listOfExpenseDistributionId);
		List<Expense_Distribution__c> listOfItems = [SELECT Id FROM Expense_Distribution__c WHERE Id IN :listOfExpenseDistributionId];
		System.assertEquals(0, listOfItems.size());

	}

	@IsTest
	static void sendEmailWithExpensesTest(){

	  List<EmailTemplate> listOfEmailTemplates = EmailService.getClassicEmailTemplates(new List<String>{'Final_Email_with_Expenses'});
      Id idOfUser = UserInfo.getUserId();
	  String email = 'test.mail@mail.com';
      List<Messaging.SingleEmailMessage> listOfSingleEmailMessages = new List<Messaging.SingleEmailMessage>();
       listOfSingleEmailMessages.add(EmailService.createClassicSingleEmail(
                        idOfUser, 
                        listOfEmailTemplates.get(0).Id, 
                        idOfUser,
                        email
        ));
		EmailService.sendListOfEmails(listOfSingleEmailMessages);
		}

}