force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Distribution__c/Expense_Distribution__c.object-meta.xml
<CustomObject>
    <label>Expense Distribution</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Distribution__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee related with the Expense Distribution</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <description>Total paid amount of the Expense Distribution</description>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EmailService.cls
public with sharing class EmailService {
  
    public static List<EmailTemplate> getClassicEmailTemplates(List<String> listOfDeveloperNames) {
        return [
            SELECT Id, Subject, Description, HtmlValue, DeveloperName, Body
            FROM EmailTemplate
            WHERE DeveloperName IN:listOfDeveloperNames
        ];
    }

    public static Messaging.SingleEmailMessage createClassicSingleEmail(Id targetObjectId, Id templateId, Id whatId, String email) {
        System.debug('email ' + email);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(targetObjectId);
        mail.setTemplateId(templateId);
        mail.setWhatId(whatId);
        if(email !=null) {
            mail.setToAddresses(new String[] { email });
        }
        mail.setBccSender(false);
        mail.setSaveAsActivity(false);

        return mail;
    }

    public static void sendListOfEmails(List<Messaging.SingleEmailMessage> listOfSingleEmailMessages) {
        try {
            if(!listOfSingleEmailMessages.isEmpty()){
                Messaging.sendEmail(listOfSingleEmailMessages);
            }
        } catch (Exception e) {
            LoggerService.saveApexLog('Payment email not delivered', e.getMessage());
        }
    }

    public static List<Expense_Distribution__c> getExpenseDistributions() {
        return [SELECT Id, Name, Employee__c, Employee__r.Name, Expense__c, Expense__r.Name, Amount__c, Paid_Amount__c FROM Expense_Distribution__c];
    }
    
}