force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Total cost of the Expense</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Expense</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Trip</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <description>Designation of the Trip (Ex: “Trip to Geneva”)</description>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <description>Total cost of the Trip</description>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExpenseTriggerHandlerTest.cls
@isTest
private class ExpenseTriggerHandlerTest {
    
    @isTest
    static void onAfterInsertTest() {

        ExpenseTriggerHandler triggerHandler = new ExpenseTriggerHandler();

        Trip__c newTrip = new Trip__c(Name =  'Test Name', Designation__c = 'Test Designation', Description__c = 'Test Description', Total_Cost__c = 0);
        insert newTrip;

		Expense__c newExpense = new Expense__c(Trip__c = newTrip.Id, Status__c = 'New', Cost__c = 10000);
        List<Expense__c> listOfNewExpenses =new List<Expense__c>();
        listOfNewExpenses.add(newExpense);
        insert listOfNewExpenses;

        Test.startTest();
        triggerHandler.onAfterInsert(listOfNewExpenses);
        Test.stopTest();
    }

    @IsTest
    static void onBeforeDeleteTest() {
        ExpenseTriggerHandler triggerHandler = new ExpenseTriggerHandler();

        Set<Id> setOfIds = new Set<Id>();

        Trip__c newTrip = new Trip__c(Name =  'Test Name', Designation__c = 'Test Designation', Description__c = 'Test Description', Total_Cost__c = 0);
        insert newTrip;

		Expense__c newExpense = new Expense__c(Trip__c = newTrip.Id, Status__c = 'New', Cost__c = 10000);
        List<Expense__c> listOfNewExpenses =new List<Expense__c>();
        listOfNewExpenses.add(newExpense);
        insert listOfNewExpenses;

        for(Expense__c item : listOfNewExpenses) {
            setOfIds.add(item.Id);
        }
        List<Expense__c> listOfOldExpense = [SELECT Id FROM Expense__c WHERE Id IN : setOfIds];
        Test.startTest();
        triggerHandler.onBeforeDelete(listOfOldExpense);
        delete listOfOldExpense;
        Test.stopTest();

    }

    @IsTest
    static void onAfterUpdateTest() {
        ExpenseTriggerHandler triggerHandler = new ExpenseTriggerHandler();
        

        Trip__c newTrip = new Trip__c(Name =  'Test Name', Designation__c = 'Test Designation', Description__c = 'Test Description', Total_Cost__c = 0);
        insert newTrip;

		Expense__c newExpense = new Expense__c(Trip__c = newTrip.Id, Status__c = 'New', Cost__c = 10000);
        List<Expense__c> listOfNewExpenses =new List<Expense__c>();
        List<Expense__c> listOfUpdateExpenses =new List<Expense__c>();

        Map<Id,Expense__c> oldMap = new Map<Id, Expense__c>();
         Map<Id,Expense__c> newMap = new Map<Id, Expense__c>();
        listOfNewExpenses.add(newExpense);
        insert listOfNewExpenses;

        for(Expense__c item : listOfNewExpenses) {
            oldMap.put(item.Id, item);
            item.Cost__c = 100;
            listOfUpdateExpenses.add(item);
        }
        update listOfUpdateExpenses;

        for(Expense__c item : listOfUpdateExpenses) {
            newMap.put(item.Id, item);
        }
        Test.startTest();
        triggerHandler.onAfterUpdate(oldMap, newMap);
        Test.stopTest();
    }
}