force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Total cost of the Expense</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Amount__c</fullName>
    <description>Total paid amount of the Expense</description>
    <label>Total Paid Amount</label>
    <summarizedField>Expense_Distribution__c.Paid_Amount__c</summarizedField>
    <summaryForeignKey>Expense_Distribution__c.Expense__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Total_Unpaid_Employees__c.field-meta.xml
<CustomField>
    <fullName>Total_Unpaid_Employees__c</fullName>
    <description>Total number of employees that didn’t paid all the expense yet</description>
    <label>Total Unpaid Employees</label>
    <summaryFilterItems>
        <field>Expense_Distribution__c.is_Full_Amount_Paid__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Expense_Distribution__c.Expense__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/Expense_Distribution__c.object-meta.xml
<CustomObject>
    <label>Expense Distribution</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Distribution__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee related with the Expense Distribution</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <description>Total paid amount of the Expense Distribution</description>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <description>Designation of the Trip (Ex: “Trip to Geneva”)</description>
    <label>Designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Last day of the Trip</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>First day of the Trip</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <description>Total cost of the Trip</description>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Total_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_Days__c</fullName>
    <formula>End_Date__c  -  Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Total_Participants__c.field-meta.xml
<CustomField>
    <fullName>Total_Participants__c</fullName>
    <description>Total number of Employees in the Trip</description>
    <label>Total Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Total_Vacation_Days_Required__c.field-meta.xml
<CustomField>
    <fullName>Total_Vacation_Days_Required__c</fullName>
    <formula>(5 * FLOOR( ( End_Date__c  - DATE( 1900, 1, 8) ) / 7 ) 
    + MIN( 5, MOD( End_Date__c - DATE( 1900, 1, 8), 7 )  ) 
) - 
(5 * FLOOR( ( Start_Date__c - DATE( 1900, 1, 8) ) / 7 ) 
      + MIN( 5, MOD( Start_Date__c - DATE( 1900, 1, 8), 7 ) ) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Vacation Days Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomDatatableService.cls
public with sharing class CustomDatatableService {

    @AuraEnabled(cacheable=true)
    public static List<Expense__c> getExpenses() {
      return [SELECT Id, Name, Cost__c, Responsible__c, Responsible__r.Name, Status__c,
                     Total_Paid_Amount__c, Total_Unpaid_Employees__c, Trip__c, Trip__r.Name
              FROM Expense__c];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Trip__c> getTrips() {
      return [SELECT Id, Name, Designation__c, Start_Date__c, End_Date__c, Total_Cost__c, Total_Days__c, Total_Participants__c, Total_Vacation_Days_Required__c FROM Trip__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Expense_Distribution__c> getExpenseDistributions() {
      return [SELECT Id, Name, Employee__c, Employee__r.Name, Expense__c, Expense__r.Name, Amount__c, Paid_Amount__c FROM Expense_Distribution__c];
    }

    @AuraEnabled
    public static void saveExpenseDistributionValues(Object data) {
        List<Expense_Distribution__c> listOfExpenseDistribution = (List<Expense_Distribution__c>) JSON.deserialize(
            JSON.serialize(data),
            List<Expense_Distribution__c>.class
        );
        upsert listOfExpenseDistribution;
    }

    @AuraEnabled
    public static void deleteExpenseDistributionRecord(List<Id> listOfExpenseDistributionId){
        delete [SELECT Id FROM Expense_Distribution__c WHERE Id IN :listOfExpenseDistributionId];
    }

    @AuraEnabled
    public static void sendEmailWithExpenses(String email){

      List<EmailTemplate> listOfEmailTemplates = EmailService.getClassicEmailTemplates(new List<String>{'Final_Email_with_Expenses'});
      Id idOfUser = UserInfo.getUserId();

      if(!listOfEmailTemplates.isEmpty()) {
        List<Messaging.SingleEmailMessage> listOfSingleEmailMessages = new List<Messaging.SingleEmailMessage>();
        listOfSingleEmailMessages.add(EmailService.createClassicSingleEmail(
                        idOfUser, 
                        listOfEmailTemplates.get(0).Id, 
                        idOfUser,
                        email
        ));
        EmailService.sendListOfEmails(listOfSingleEmailMessages);

      }

    }

  }

  