force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Total cost of the Expense</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Number_of_Expense_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Expense_Distribution__c</fullName>
    <label>Number of Expense Distribution</label>
    <summaryForeignKey>Expense_Distribution__c.Expense__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/Expense_Distribution__c.object-meta.xml
<CustomObject>
    <label>Expense Distribution</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Distribution__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <description>Total cost of the Trip</description>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Total_Participants__c.field-meta.xml
<CustomField>
    <fullName>Total_Participants__c</fullName>
    <description>Total number of Employees in the Trip</description>
    <label>Total Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExpenseTriggerHandler.cls
public with sharing class ExpenseTriggerHandler {
    
    public void onAfterUpdate( Map<Id,Expense__c> oldMap, Map<Id,Expense__c> newMap) {
        List<Expense__c> listOfUpdatedExpenses = new List<Expense__c>();

        if(!newMap.isEmpty()) {
            for(Expense__c employee :newMap.values()){
                listOfUpdatedExpenses.add(employee);
            }
        }
        if(listOfUpdatedExpenses != null) {
            fillTotalParticipantsOfTrip(listOfUpdatedExpenses);
            updateAmountOfExpenseDistrubution(listOfUpdatedExpenses);
        }   
    }

    public void onAfterInsert(List<Expense__c> listOfNewExpenses) {
        fillTotalCostOfTrip(listOfNewExpenses);
    }

    public void onBeforeDelete(List<Expense__c> listOfOldExpenses) {
        deleteTotalCostOfTrip(listOfOldExpenses);
    }

    private void fillTotalCostOfTrip(List<Expense__c> listOfNewExpenses) {
        Map<Id, Decimal> mapOfTripByCost = new Map<Id, Decimal>();	
        for(Expense__c expense : listOfNewExpenses) {
            mapOfTripByCost.put(expense.Trip__c, expense.Cost__c);
        }

        List<Trip__c> listOfTrips = [SELECT Id, Total_Cost__c FROM Trip__c WHERE Id IN :mapOfTripByCost.keySet()];

        for(Trip__c trip : listOfTrips) {
            if(trip.Total_Cost__c == null){
                trip.Total_Cost__c = mapOfTripByCost.get(trip.Id);
            } else {
                trip.Total_Cost__c += mapOfTripByCost.get(trip.Id);
            }
        }

        update listOfTrips;
    }

    private void deleteTotalCostOfTrip(List<Expense__c> listOfOldExpenses) {
        Map<Id, Decimal> mapOfTripByCost = new Map<Id, Decimal>();	
        Set<Id> setOfExpenseId = new Set<Id>();
        for(Expense__c expense : listOfOldExpenses) {
            setOfExpenseId.add(expense.Id);
            //mapOfTripByCost.put(expense.Trip__c, expense.Cost__c);
        }
        List<Expense__c> listOfExpenses = [SELECT Id, Cost__c, Trip__c FROM Expense__c WHERE Id IN :setOfExpenseId];
        for(Expense__c expense : listOfExpenses) {
            mapOfTripByCost.put(expense.Trip__c, expense.Cost__c);
        }


        List<Trip__c> listOfTrips = [SELECT Id, Total_Cost__c FROM Trip__c WHERE Id IN :mapOfTripByCost.keySet()];

        for(Trip__c trip : listOfTrips) {
            trip.Total_Cost__c -= mapOfTripByCost.get(trip.Id);
        }

        update listOfTrips;
    }

    private void fillTotalParticipantsOfTrip(List<Expense__c> listOfExpenses) {

        Map<Id, Decimal> mapOfTripByNumberExpenseDistribution = new Map<Id, Decimal>();	
        for(Expense__c expense : listOfExpenses) {
            mapOfTripByNumberExpenseDistribution.put(expense.Trip__c, expense.Number_of_Expense_Distribution__c);
        }

        List<Trip__c> listOfTrips = [SELECT Id, Total_Participants__c FROM Trip__c WHERE Id IN :mapOfTripByNumberExpenseDistribution.keySet()];

        for(Trip__c trip : listOfTrips) {
            trip.Total_Participants__c = mapOfTripByNumberExpenseDistribution.get(trip.Id);
        }

        update listOfTrips;
    }

    private void updateAmountOfExpenseDistrubution(List<Expense__c> listOfExpenses) {

        Set<Id> setOfExpenseIds = new Set<Id>();
        
        for(Expense__c expense : listOfExpenses) {
            setOfExpenseIds.add(expense.Id);
        }
        List<Expense_Distribution__c> listOfExpenseDistribution = [SELECT Id, Expense__c,Amount__c, Expense__r.Number_of_Expense_Distribution__c, Expense__r.Cost__c FROM Expense_Distribution__c WHERE Expense__c IN : setOfExpenseIds];

        if(!listOfExpenseDistribution.isEmpty()){
            for(Expense_Distribution__c expenseDistribution : listOfExpenseDistribution) {
                expenseDistribution.Amount__c = expenseDistribution.Expense__r.Cost__c / expenseDistribution.Expense__r.Number_of_Expense_Distribution__c;
            }
            update listOfExpenseDistribution;
        }


    }
}