force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Total cost of the Expense</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/Expense_Distribution__c.object-meta.xml
<CustomObject>
    <label>Expense Distribution</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Distribution__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>Expense</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <description>Total paid amount of the Expense Distribution</description>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ExpenseDistributionTriggerHandlerTest.cls
@isTest
private class ExpenseDistributionTriggerHandlerTest {
   
    @IsTest
    static void onAfterUpdateTest() {
        ExpenseDistributionTriggerHandler triggerHandler = new ExpenseDistributionTriggerHandler();

        Expense__c newExpense = new Expense__c(Status__c = 'New', Cost__c = 10000);
        insert newExpense;

        List<Expense_Distribution__c> listOfnewExpenseDistributions = new List<Expense_Distribution__c>();
        Expense_Distribution__c newExpenseDistributions = new Expense_Distribution__c(Expense__c = newExpense.Id, Paid_Amount__c = 100);
        listOfnewExpenseDistributions.add(newExpenseDistributions);
        insert listOfnewExpenseDistributions;

        Test.startTest();
        triggerHandler.onAfterInsert(listOfnewExpenseDistributions);
        Test.stopTest();
    }
}