force-app/main/default/objects/Expense_Distribution__c/Expense_Distribution__c.object-meta.xml
<CustomObject>
    <label>Expense Distribution</label>
    <nameField>
        <displayFormat>ED-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Distributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Distribution__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee related with the Expense Distribution</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Expense Distributions</relationshipLabel>
    <relationshipName>Expense_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Distribution__c/fields/is_Full_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>is_Full_Amount_Paid__c</fullName>
    <formula>Amount__c   &lt;= Paid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>is Full Amount Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExpenseDistributionTriggerHandler.cls
public with sharing class ExpenseDistributionTriggerHandler {
    
    public void onAfterInsert(List<Expense_Distribution__c> listOfNewExpenseDistribution) {
        sendEmailNotificationWhenExpenseDistributionPaid(listOfNewExpenseDistribution);
    }

    public void onAfterUpdate(Map<Id,Expense_Distribution__c> oldMap, Map<Id,Expense_Distribution__c> newMap) {
        List<Expense_Distribution__c> listOfUpdatedExpenseDistributions = new List<Expense_Distribution__c>();

        if(!newMap.isEmpty()) {
            for(Expense_Distribution__c expenseDistributions :newMap.values()){
                if(expenseDistributions.is_Full_Amount_Paid__c != oldMap.get(expenseDistributions.Id).is_Full_Amount_Paid__c){
                    listOfUpdatedExpenseDistributions.add(expenseDistributions);
                }
            }
        }
        if(listOfUpdatedExpenseDistributions != null) {
            sendEmailNotificationWhenExpenseDistributionPaid(listOfUpdatedExpenseDistributions);
        } 
    }

    private void sendEmailNotificationWhenExpenseDistributionPaid(List<Expense_Distribution__c> listOfNewOrUpdatedExpenseDistribution) {
        System.debug('im here');
        Map<Id, List<Expense_Distribution__c>> mapOfExpensesForEmailById = new Map<Id, List<Expense_Distribution__c>>();
        Set<Id> setOfExpenseDistribution = new Set<Id>();

        for(Expense_Distribution__c expenseDistribution : listOfNewOrUpdatedExpenseDistribution) {
            setOfExpenseDistribution.add(expenseDistribution.Id);
        }
        List<Expense_Distribution__c> listOExpenseDistribution = [SELECT Id, is_Full_Amount_Paid__c, Employee__c, Employee__r.Contact__c FROM Expense_Distribution__c WHERE Id IN :setOfExpenseDistribution];
        for(Expense_Distribution__c expenseDistribution : listOExpenseDistribution) {
            if(expenseDistribution.is_Full_Amount_Paid__c == true) {
                mapOfExpensesForEmailById.put(expenseDistribution.Id, new List<Expense_Distribution__c>{expenseDistribution});
            }
        }
        System.debug('mapOfExpensesForEmailById ' + mapOfExpensesForEmailById);

        List<EmailTemplate> listOfEmailTemplates = EmailService.getClassicEmailTemplates(new List<String>{'Expense_Distribution_was_paid'});

        if(!listOfEmailTemplates.isEmpty()) {
            List<Messaging.SingleEmailMessage> listOfSingleEmailMessages = new List<Messaging.SingleEmailMessage>();

            for (Id expenseDistributionId : mapOfExpensesForEmailById.keySet()) {
                for (Expense_Distribution__c expenseDistribution : mapOfExpensesForEmailById.get(expenseDistributionId)) {
                    listOfSingleEmailMessages.add(EmailService.createClassicSingleEmail(
                        expenseDistribution.Employee__r.Contact__c, 
                        listOfEmailTemplates.get(0).Id, 
                        expenseDistributionId,
                        null
                    ));
                }
            }

            EmailService.sendListOfEmails(listOfSingleEmailMessages);
        }

    }
}